name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore List/List.sln
    - name: Build
      run: dotnet build List/List.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test List/List.sln --no-restore --verbosity normal
